<template>
    <nav>
        <ul>
            <li>
                Movies
            </li>
            <li>
                Screenings
            </li>
            <li>
                Pricing
            </li>
        </ul>
        <div>
            <button>
                Login
            </button>
            <button>
                Register
            </button>
        </div>
    </nav>
</template>