<template>
    <nav>
        <ul>
            <li>
                Movies
            </li>
            <li>
                Screenings
            </li>
            <li>
                Pricing
            </li>
        </ul>
    </nav>
</template>